config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                  Controller#Action
#         root GET    /                            pages#home
#        users GET    /users(.:format)             users#index
#              POST   /users(.:format)             users#create
#     new_user GET    /users/new(.:format)         users#new
#         user PATCH  /users/:id(.:format)         users#update
#              PUT    /users/:id(.:format)         users#update
#    edit_user GET    /users/edit(.:format)        users#edit
#     comments GET    /comments(.:format)          comments#index
#              POST   /comments(.:format)          comments#create
#  new_comment GET    /comments/new(.:format)      comments#new
# edit_comment GET    /comments/:id/edit(.:format) comments#edit
#      comment GET    /comments/:id(.:format)      comments#show
#              PATCH  /comments/:id(.:format)      comments#update
#              PUT    /comments/:id(.:format)      comments#update
#              DELETE /comments/:id(.:format)      comments#destroy
#        login GET    /login(.:format)             session#new
#              POST   /login(.:format)             session#create
#              DELETE /login(.:format)             session#destroy

Rails.application.routes.draw do
  root :to => 'pages#new'
  get 'garden' => 'pages#garden', :as => :garden
  get 'garden/team' => 'pages#team', :as => :garden_team
  resources :users, :only => [:new, :create, :update, :index]
  get '/users/edit' => 'users#edit', :as => :edit_user
  resources :comments, :except => :index
  

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  content    :text
#  category   :text
#  post_date  :date
#  emotion    :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
    belongs_to :user, :optional => true
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  name       :text
#  start_date :date
#  difficulty :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Task < ApplicationRecord
    belongs_to :user, :optional => true
end

app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id         :bigint           not null, primary key
#  name       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Team < ApplicationRecord
    has_many :users
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  name            :text
#  email           :text
#  admin           :boolean          default(FALSE)
#  team_id         :integer
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
    has_secure_password

    validates :email, :presence => true , :uniqueness => true
    has_many :comments
    has_many :tasks
    belongs_to :team, :optional => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user

    private
    def fetch_user
        @current_user = User.find_by :id =>session[:user_id] if session[:user_id].present?
        session[:user_id] = nil unless @current_user.present?
    end

    def check_for_login
        redirect_to login_path unless @current_user.present?
    end

    def check_for_admin
        redirect_to root_path unless @current_user.present? && @current_user.admin?
    end

    def check_for_daily_comment
        redirect_to new_comment_path unless @current_user.comments.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).present?
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_for_login


  def new
    if @current_user.comments.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).present?
      @message = "You already posted your feelings today."
      redirect_to garden_path 
    end
    @comment = Comment.new
  end

  def create
    @comment = Comment.create comment_params
    @comment.update_attribute(:user_id, @current_user.id)
    redirect_to garden_path
  end

  def edit
    @comment = @current_user.comments.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).first
    gon.current_user = @current_user
  end

  def update 
    comment = @current_user.comments.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).first
    comment.update comment_params
    redirect_to comment
  end

  def index
    id = @current_user.id
    @comments = Comment.where(user_id: id)
  end

  def show
    id = @current_user.id
    @comments = Comment.where(user_id: id)
  end

  def destroy
    comment = Comment.find params[:id]
    comment.destroy
    redirect_to comments_path
  end

  private
  def comment_params
    params.required(:comment).permit(:content, :category, :emotion, :user_id, :score)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :check_for_login, :except => :new
  before_action :check_for_daily_comment, :only => [:garden, :team]

  def new
  end

  def garden

    @user = User.find @current_user.id
    @score = @user.comments.last.score
    gon.score = @score
  end
  
  def team
    @score = team_score
    gon.score = @score
    @user = User.find @current_user.id
    @team = @user.team
  end



  private
  # get average emotion score from the date
  # TODO: change it to only get average of current team
  def team_score
    team_member = @current_user.team.users
    team_comment = Comment.where(user_id: team_member.pluck('id'))
    emotion_scores = team_comment.where('created_at BETWEEN ? AND ?', DateTime.now.beginning_of_day, DateTime.now.end_of_day).average(:score)
    emotion_scores
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create 
    user = User.find_by :email => params[:email]

    if user.present? && user.authenticate(params[:password]) 
      session[:user_id] = user.id
      redirect_to new_comment_path
    else
      flash[:error_message] = "invalid email or password"
      redirect_to login_path
    end
  end

  def destroy 
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_login, :only => [:edit, :update]
  before_action :check_for_admin, :only => [:index]
  
  def new
    if @current_user.present? 
      redirect_to new_comment_path
    end
    @user = User.new
  end
  
    def index
      @users = User.all 
    end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to new_comment_path
      session[:user_id] = @user.id 
    else 
      render :new
    end
  end

  def edit
    @user = @current_user
  end

  def update
    @current_user.update user_params
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :team_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment do |f| %>
<div class="row justify-content-md-center">
    <div class="col col-md-5">
    <div class="form-group">
    <%= f.label :content, "Comment" %>
    <%= f.text_field :content, :class => "form-control", :id => "exampleFormControlInput1" , :placeholder => "Express your feelings within 120 characters" %>
    </div>
    <div class="form-group">
    <%= f.label :category %>
    <%= f.select :category, options_for_select(["work", "human resource", "environment", "other"]), :class => 'form-control', :id => "exampleFormControlSelect1" %>
    </div>

<div class="form-check form-check-inline">
  <input class="form-check-input" type="radio" id="inlineRadio1" value="happy" name="comment[emotion]">
  <label class="form-check-label" for="emotion"><i class="fas fa-grin-squint fa-5x"></i></label>

</div>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="radio" id="inlineRadio2" value="sad" name="comment[emotion]">
  <label class="form-check-label" for="emotion"><i class="fas fa-sad-tear fa-5x"></i></label>
</div>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="radio" id="inlineRadio3" value="angry" name="comment[emotion]">
  <label class="form-check-label" for="emotion"><i class="fas fa-angry fa-5x"></i></label>
</div>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="radio" id="inlineRadio4" value="alright" name="comment[emotion]">
  <label class="form-check-label" for="emotion"><i class="fas fa-meh fa-5x"></i></label>
</div>

    <div class="form-group">
    <%= f.label :score, "Stress level" %>
    <%= f.range_field :score, in: 1..10, :class => "form-control-range", :id => "formControlRange" %>
    </div>
    <%= f.submit %>
    </div>
    </div>


    <% end %>

app/views/comments/edit.html.erb
<div class="userBackground">

<h1>Edit comment</h1>

<%= link_to "show comment history", comment_path(@current_user) %>
<%= render :partial => 'form' %>

</div>

app/views/comments/new.html.erb
<div class="userBackground">


<h1>How are you feeling today</h1>

<%= render :partial => 'form' %>
</div>

app/views/comments/show.html.erb
<div class="userBackground">


<h1>Comments history</h1>
<div class ="showComment">
<div class="row justify-content-md-center">
    <div class="col col-md-3">
    Content
    </div>
    <div class="col col-lg-2">
    Feelings
    </div>
    <div class="col col-lg-2">
    Stress Level
    </div>
    <div class="col col-lg-2">
    Date
    </div>
</div>
<% @comments.each do |comment| %>
<div class="row justify-content-md-center">
    <div class="col col-lg-3">
    <%= comment.content %>
    </div>
    <div class="col col-lg-2">
    <%= comment.emotion %>
    </div>
    <div class="col col-lg-2">
    <%= comment.score %>
    </div>
    <div class="col col-lg-2">
    <%= comment.created_at.strftime("%b %d, %Y") %>
    </div>
    </div>
<% end %>

</div>

    <%= link_to "Back", edit_comment_path(@current_user.comments.last) %>

    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= Gon::Base.render_data %>
    <%= cloudinary_js_config %>

  </head>

  <body>
  
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgba(86, 143, 197, 0.95);">
  <a class="navbar-brand navTitle" href="/garden">Bonsai</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link navTitle" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
  <% if @current_user.present? %>
      <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_path, :class=> "nav-link" %>
        </li>
      <li class="nav-item">
        <%= link_to "Logout #{ @current_user.email }", login_path, :method => 'delete', :class=> "nav-link"  %>
      </li>    
      <% if @current_user.admin? %>     
      <li class="nav-item">
        <%= link_to "All users", users_path, :class=> "nav-link"  %>
      </li>
    <% end %>
  <% else %>
      <li class="nav-item">
        <%= link_to "Sign up", new_user_path , :class => "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Sign in", login_path, :class => "nav-link" %>
      </li>  <% end %>
    </ul>
  </div>
</nav>


    <%= yield %>
  </body>
</html>

app/views/pages/garden.html.erb
<h2>My Zen</h2>

<% if @message.present? %>
<p><%= @message %></p>
<% end %>


<div class="tree <%= @user.comments.last.emotion %> userTree">
        <p class="treeTag"><%= @user.comments.last.content %></p>

       <p class="nameTag"><%= link_to @user.name, edit_comment_path(@user.comments.last) %></p>
</div>


<%= link_to image_tag('swap.png', :class => "gardenSwap"), garden_team_path %>

<div class="cloud">
    <ul class="centered-clouds">
        <li></li>
        <li></li>
        <li></li>
        <li></li>
      </ul>
    </div>

<div class="raindrop"></div>

<div class="anim">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 800">
    <g fill="none" fill-rule="evenodd">
      <path d="" stroke-dasharray="undefined" style="stroke-dashoffset: 0px;"></path>
  </g></svg>
</div>
<canvas id="background"></canvas>
<div class="sun">
</div>

<div class="pedal">
</div>


  <div class="fire one"></div>
  <div class="fire two"></div>
  <div class="fire three"></div>
  <div class="fire four"></div>

app/views/pages/home.html.erb
<% if @score.present? && @score > 2 %>
<%= @score %>
<% end %>

<%= content_tag(:h2, @team.name, :class => "teamTitle")%>

<% @team.users.each do |user| %>
    <% index = 1 %>
    <% if user.id ==  @current_user.id %>
        <div class="tree <%= user.comments.last.emotion %> userTree">
            <p class="treeTag"><%= user.comments.last.content %></p>
            <%= link_to user.name, comment_path(user.id) %>
        </div>
    <% else %>
        <div class="tree <%= user.comments.last.emotion %> tree<%= index %>">
            <p class="treeTag"><%= user.comments.last.content %></p>
            <%= link_to user.name, comment_path(user.id) %>  
        <% index += 1 %>
        </div>
        <% end %>
<% end %>

<div class="cloud">
    <ul class="centered-clouds">
        <li></li>
        <li></li>
        <li></li>
        <li></li>
      </ul>
    </div>

<div class="raindrop"></div>

<div class="anim">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 800">
    <g fill="none" fill-rule="evenodd">
      <path d="" stroke-dasharray="undefined" style="stroke-dashoffset: 0px;"></path>
  </g></svg>
</div>
<canvas id="background"></canvas>
<div class="sun">
</div>

<div class="pedal">
</div>


  <div class="fire one"></div>
  <div class="fire two"></div>
  <div class="fire three"></div>
  <div class="fire four"></div>

app/views/pages/new.html.erb
<div class="welcomeBackground">
<div class="welcomeLogo">
<h1>Bonsai</h1>

<p>Take a breather, relax and chill.</p>


</div>
</div>

app/views/pages/team.html.erb
<%= content_tag(:h2, @team.name, :class => "teamTitle")%>

    <% index = 1 %>
<% @team.users.each do |user| %>
    <% if user.id ==  @current_user.id %>
        <div class="tree <%= user.comments.last.emotion %> userTree">
            <p class="treeTag"><%= user.comments.last.content %></p>
            <p class="nameTag"><%= link_to user.name, comment_path((@user.comments.last)) %></p>
        </div>
    <% elsif user.comments.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).present? %>
        <div class="tree <%= user.comments.last.emotion %> tree<%= index %>">
            <p class="treeTag"><%= user.comments.last.content %></p>
            <p class="nameTag"><%= user.name %> </p>
        </div>
        <% end %>
            <% index += 1 %>
<% end %>
<%= link_to image_tag('swap.png', :class => "gardenSwap"), garden_path %>

<div class="cloud">
    <ul class="centered-clouds">
        <li></li>
        <li></li>
        <li></li>
        <li></li>
      </ul>
    </div>

<div class="raindrop"></div>

<div class="anim">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 800">
    <g fill="none" fill-rule="evenodd">
      <path d="" stroke-dasharray="undefined" style="stroke-dashoffset: 0px;"></path>
  </g></svg>
</div>
<canvas id="background"></canvas>
<div class="sun">
</div>

<div class="pedal">
</div>


  <div class="fire one"></div>
  <div class="fire two"></div>
  <div class="fire three"></div>
  <div class="fire four"></div>

app/views/session/new.html.erb
<div class="userBackground">

<h1>Log in</h1>
<p><%= flash[:error_message] %></p>

<%= form_tag login_path do %>
    <%= label_tag :email %>
    <%= email_field_tag :email %>

    <%= label_tag :password %>
    <%= password_field_tag :password %>

    <%= submit_tag "Sign in" %>

<% end %>
</div>

app/views/users/edit.html.erb
<div class="userBackground">

<div class="redMonkey">
</div>
<h1>Edit User</h1>


<div class="row">
    <div class="col col-md-8"></div>
    <div class="col col-md-3">
<%= form_for @user do |f| %>
<div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
 </div>
  <div class="form-group">  
    <%= f.label :email %>
    <%= f.email_field :email, :id => "exampleInputEmail1", :class => "form-control", :placeholder => "Enter email" %>
     </div>
 <div class="form-group">
    <%= f.label :team_id %>
    <%= f.select :team_id, Team.all.collect { |t| [t.name, t.id] } %>
     </div>
<div class="form-group" id="signUp">
    <%= f.submit "Update", :class => "btn btn-outline-info btn-sm" %>
    </div>
    </div>
    <div class="col col-md-3">
</div>
    <% end %>
    </div>

app/views/users/index.html.erb
<div class="userBackground">

<h1>All Users</h1>

<% @users.each do |user| %>
   <p> <%= user.name %>, <%= user.email %></p>
   <% end %>
   </div>

app/views/users/new.html.erb
<div class="userBackground">
<h2>New User</h2>
<% if @user.errors.any? %>
    <ol>
    <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ol>
<% end %>

<div class="monkey">
</div>

<div class="row">
    <div class="col col-md-8"></div>
    <div class="col col-md-3">
<%= form_for @user do |f| %>
<div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
 </div>
 <div class="form-group">  
    <%= f.label :email %>
    <%= f.email_field :email, :id => "exampleInputEmail1", :class => "form-control", :placeholder => "Enter email" %>
     </div>
 <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, :class => "form-control", :id => "exampleInputPassword1", :placeholder => "Enter password" %>
     </div>
 <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class => "form-control", :id => "exampleInputPassword1", :placeholder => "Confirm password" %>
    </div>
 <div class="form-group">
    <%= f.label :team_id %>
    <%= f.select :team_id, Team.all.collect { |t| [t.name, t.id] } %>
     </div>
<div class="form-group" id="signUp">
    <%= f.submit "Sign up", :class => "btn btn-outline-info btn-sm" %>
    </div>
    </div>
    <div class="col col-md-3">
</div>
    <% end %>
    </div>
</div>